"""
parity_test.py — Automated cross-validation parity test suite for numba_ops.

Compares outputs from compiled Cython implementation (_numba_ops_core) and
Python fallback implementation (_numba_ops_core_python) across randomized,
physically valid input domains generated by Hypothesis.
"""

import pytest
import numpy as np
from hypothesis import given, strategies as st, settings

# Attempt importing compiled core vs fallback core
try:
    from physical_engine.optimization import _numba_ops_core as core_c
    COMPILED_AVAILABLE = True
except ImportError:
    core_c = None
    COMPILED_AVAILABLE = False

from physical_engine.optimization import _numba_ops_core_python as core_py
from physical_engine.optimization import numba_ops

pytestmark = pytest.mark.skipif(
    not COMPILED_AVAILABLE,
    reason="Compiled _numba_ops_core extension is not available."
)

# ── Shared strategies for physical input domains ──────────────────────────

st_temp = st.floats(min_value=273.15 + 10, max_value=273.15 + 150, allow_nan=False, allow_infinity=False)
st_press = st.floats(min_value=1e5, max_value=1e7, allow_nan=False, allow_infinity=False)
st_current_density = st.floats(min_value=1e-3, max_value=3.0, allow_nan=False, allow_infinity=False)


# ── Registered test kernels map for coverage check ────────────────────────
TESTED_KERNELS = set()


def register_tested(func_name: str):
    TESTED_KERNELS.add(func_name)


# ── Parity Tests ──────────────────────────────────────────────────────────

@settings(max_examples=100, deadline=None)
@given(
    j=st_current_density,
    T=st_temp,
    P_op=st_press,
    R=st.just(8.314),
    F=st.just(96485.0),
    z=st.just(2.0),
    alpha=st.floats(min_value=0.3, max_value=0.7),
    j0=st.floats(min_value=1e-9, max_value=1e-3),
    j_lim=st.floats(min_value=3.5, max_value=10.0),
    delta_mem=st.floats(min_value=1e-5, max_value=1e-3),
    sigma_base=st.floats(min_value=0.01, max_value=0.2),
    P_ref=st.just(101325.0)
)
def test_calculate_pem_voltage_jit(j, T, P_op, R, F, z, alpha, j0, j_lim, delta_mem, sigma_base, P_ref):
    register_tested("calculate_pem_voltage_jit")
    fn_c = getattr(core_c, "calculate_pem_voltage_jit")
    fn_py = getattr(core_py, "calculate_pem_voltage_jit")
    res_c = fn_c(j, T, P_op, R, F, z, alpha, j0, j_lim, delta_mem, sigma_base, P_ref)
    res_py = fn_py(j, T, P_op, R, F, z, alpha, j0, j_lim, delta_mem, sigma_base, P_ref)
    assert np.allclose(res_c, res_py, rtol=1e-7, atol=1e-9)


@settings(max_examples=100, deadline=None)
@given(
    T=st_temp,
    P=st_press,
    n_stage=st.integers(min_value=1, max_value=5),
    eta_poly=st.floats(min_value=0.7, max_value=0.95),
    gamma=st.floats(min_value=1.2, max_value=1.4)
)
def test_calculate_compression_work(T, P, n_stage, eta_poly, gamma):
    register_tested("calculate_compression_work")
    fn_c = getattr(core_c, "calculate_compression_work")
    fn_py = getattr(core_py, "calculate_compression_work")
    res_c = fn_c(T, P, n_stage, eta_poly, gamma)
    res_py = fn_py(T, P, n_stage, eta_poly, gamma)
    assert np.allclose(res_c, res_py, rtol=1e-3, atol=1e-5)


@settings(max_examples=100, deadline=None)
@given(T=st_temp)
def test_antoine_psat_water(T):
    register_tested("_antoine_psat_water")
    fn_c = getattr(core_c, "_antoine_psat_water")
    fn_py = getattr(core_py, "_antoine_psat_water")
    assert np.allclose(fn_c(T), fn_py(T), rtol=1e-7, atol=1e-9)


@settings(max_examples=100, deadline=None)
@given(T=st_temp)
def test_calculate_water_psat_jit(T):
    register_tested("calculate_water_psat_jit")
    fn_c = getattr(core_c, "calculate_water_psat_jit")
    fn_py = getattr(core_py, "calculate_water_psat_jit")
    assert np.allclose(fn_c(T), fn_py(T), rtol=1e-7, atol=1e-9)


@settings(max_examples=100, deadline=None)
@given(
    T=st_temp,
    a=st.floats(min_value=20.0, max_value=40.0),
    b=st.floats(min_value=-0.01, max_value=0.01),
    c=st.floats(min_value=1e-6, max_value=1e-4),
    d=st.floats(min_value=-1e-8, max_value=-1e-10),
    e=st.floats(min_value=0.0, max_value=1e-3)
)
def test_integral_cp(T, a, b, c, d, e):
    register_tested("_integral_cp")
    fn_c = getattr(core_c, "_integral_cp")
    fn_py = getattr(core_py, "_integral_cp")
    coeffs = np.array([a, b, c, d, e], dtype=np.float64)
    assert np.allclose(fn_c(T, coeffs), fn_py(T, coeffs), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    x=st.floats(min_value=0.0, max_value=1.0),
    y=st.floats(min_value=0.0, max_value=1.0)
)
def test_bilinear_interp_jit(x, y):
    register_tested("bilinear_interp_jit")
    grid_x = np.array([0.0, 1.0], dtype=np.float64)
    grid_y = np.array([0.0, 1.0], dtype=np.float64)
    data = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float64)
    fn_c = getattr(core_c, "bilinear_interp_jit")
    fn_py = getattr(core_py, "bilinear_interp_jit")
    assert np.allclose(fn_c(grid_x, grid_y, data, x, y), fn_py(grid_x, grid_y, data, x, y), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    h_in=st.floats(min_value=10.0, max_value=100.0),
    h_out=st.floats(min_value=10.0, max_value=100.0),
    d_in=st.floats(min_value=0.01, max_value=0.1),
    d_out=st.floats(min_value=0.012, max_value=0.12),
    k_wall=st.floats(min_value=10.0, max_value=50.0),
    r_foul_in=st.floats(min_value=1e-5, max_value=1e-3),
    r_foul_out=st.floats(min_value=1e-5, max_value=1e-3)
)
def test_calculate_dynamic_u_fouled(h_in, h_out, d_in, d_out, k_wall, r_foul_in, r_foul_out):
    register_tested("calculate_dynamic_u_fouled")
    fn_c = getattr(core_c, "calculate_dynamic_u_fouled")
    fn_py = getattr(core_py, "calculate_dynamic_u_fouled")
    assert np.allclose(fn_c(h_in, h_out, d_in, d_out, k_wall, r_foul_in, r_foul_out),
                       fn_py(h_in, h_out, d_in, d_out, k_wall, r_foul_in, r_foul_out), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    mass_flow=st.floats(min_value=0.1, max_value=10.0),
    area=st.floats(min_value=0.01, max_value=0.5),
    d_h=st.floats(min_value=0.01, max_value=0.2),
    mu=st.floats(min_value=1e-5, max_value=1e-3)
)
def test_calculate_reynolds_flux(mass_flow, area, d_h, mu):
    register_tested("calculate_reynolds_flux")
    fn_c = getattr(core_c, "calculate_reynolds_flux")
    fn_py = getattr(core_py, "calculate_reynolds_flux")
    assert np.allclose(fn_c(mass_flow, area, d_h, mu), fn_py(mass_flow, area, d_h, mu), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    Re=st.floats(min_value=10.0, max_value=1e5),
    Pr=st.floats(min_value=0.5, max_value=10.0)
)
def test_calculate_nusselt_crossflow(Re, Pr):
    register_tested("calculate_nusselt_crossflow")
    fn_c = getattr(core_c, "calculate_nusselt_crossflow")
    fn_py = getattr(core_py, "calculate_nusselt_crossflow")
    assert np.allclose(fn_c(Re, Pr), fn_py(Re, Pr), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    Re=st.floats(min_value=3000.0, max_value=1e5),
    Pr=st.floats(min_value=0.5, max_value=10.0)
)
def test_calculate_nusselt_dittus_boelter(Re, Pr):
    register_tested("calculate_nusselt_dittus_boelter")
    fn_c = getattr(core_c, "calculate_nusselt_dittus_boelter")
    fn_py = getattr(core_py, "calculate_nusselt_dittus_boelter")
    assert np.allclose(fn_c(Re, Pr, True), fn_py(Re, Pr, True), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    NTU=st.floats(min_value=0.1, max_value=5.0),
    Cr=st.floats(min_value=0.01, max_value=0.99)
)
def test_counter_flow_ntu_effectiveness(NTU, Cr):
    register_tested("counter_flow_ntu_effectiveness")
    fn_c = getattr(core_c, "counter_flow_ntu_effectiveness")
    fn_py = getattr(core_py, "counter_flow_ntu_effectiveness")
    assert np.allclose(fn_c(NTU, Cr), fn_py(NTU, Cr), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    NTU=st.floats(min_value=0.1, max_value=5.0),
    Cr=st.floats(min_value=0.01, max_value=0.99)
)
def test_dry_cooler_ntu_effectiveness(NTU, Cr):
    register_tested("dry_cooler_ntu_effectiveness")
    fn_c = getattr(core_c, "dry_cooler_ntu_effectiveness")
    fn_py = getattr(core_py, "dry_cooler_ntu_effectiveness")
    assert np.allclose(fn_c(NTU, Cr), fn_py(NTU, Cr), rtol=1e-7, atol=1e-9)


@settings(max_examples=50, deadline=None)
@given(
    z=st.floats(min_value=0.01, max_value=0.99),
    K=st.floats(min_value=0.1, max_value=10.0)
)
def test_solve_rachford_rice_single_condensable(z, K):
    register_tested("solve_rachford_rice_single_condensable")
    fn_c = getattr(core_c, "solve_rachford_rice_single_condensable")
    fn_py = getattr(core_py, "solve_rachford_rice_single_condensable")
    assert np.allclose(fn_c(z, K), fn_py(z, K), rtol=1e-7, atol=1e-9)


# ── Register remaining exported kernels for full coverage ────────────────

def _get_all_callable_export_names():
    constants = {
        "GAS_CP_COEFFS", "GAS_MW", "GAS_MW_KG_MOL", "HENRY_H2_C",
        "HENRY_H2_H298", "HENRY_H2_MW", "HENRY_O2_C", "HENRY_O2_H298",
        "HENRY_O2_MW", "LIQ_CP_COEFFS", "LIQ_MW", "compiled_core_status"
    }
    return [name for name in numba_ops.__all__ if name not in constants]


def _invoke_and_compare(fn_name: str):
    import inspect
    fn_c = getattr(core_c, fn_name, None)
    fn_py = getattr(core_py, fn_name, None)
    assert fn_c is not None, f"Function {fn_name} missing from compiled core"
    assert fn_py is not None, f"Function {fn_name} missing from Python core"

    sig = inspect.signature(fn_py)
    args = []
    for param in sig.parameters.values():
        name = param.name
        is_arr = "ndarray" in str(param.annotation) or (name.endswith("s") and not name.endswith("_s") and not name.startswith("dt_") and not name.startswith("N_") and not name.startswith("n_") and not name.startswith("num_") and not any(name.endswith(k) for k in ("steps", "seconds", "hours", "status", "radius", "loss", "process", "mass", "sys", "min", "max", "m3s", "tubes", "cells", "gas", "guess", "moles")) or any(k in name for k in ("grid", "luts", "weights", "fracs", "coeffs", "array", "data", "mat")))
        if param.default is not inspect.Parameter.empty:
            args.append(param.default)
        elif is_arr:
            dtype = np.int32 if any(k in name for k in ("state", "index", "indices", "flag", "map", "species")) or name in ("id", "ids") or name.endswith("_id") or name.endswith("_ids") else np.float64
            if "3d" in name or name.endswith("luts") or name.startswith("stacked_"):
                args.append(np.ones((2, 2, 2), dtype=dtype))
            elif (any(k in name for k in ("2d", "lut", "data", "mat_", "matrix", "table")) or name == "coeffs" or "cp_coeffs" in name) and "fracs" not in name:
                args.append(np.ones((2, 2), dtype=dtype))
            else:
                args.append(np.array([1, 2] if dtype == np.int64 else [1.0, 2.0], dtype=dtype))
        elif "int" in str(param.annotation) or name.startswith("n_") or name.startswith("num_") or "steps" in name or "iter" in name or "threads" in name:
            args.append(2)
        elif "bool" in str(param.annotation) or name.startswith("is_") or "flag" in name:
            args.append(True)
        else:
            args.append(1.0)

    res_c = fn_c(*args)
    res_py = fn_py(*args)

    if res_c is None and res_py is None:
        return
    if isinstance(res_c, tuple):
        for item_c, item_py in zip(res_c, res_py):
            if item_c is not None:
                assert np.allclose(item_c, item_py, rtol=1e-4, atol=1e-6)
    else:
        assert np.allclose(res_c, res_py, rtol=1e-4, atol=1e-6)


def test_all_kernels_covered():
    """Verify that all callable kernels exported in numba_ops.__all__ are tested numerically."""
    exported_callables = set(_get_all_callable_export_names())

    untested = sorted(list(exported_callables - TESTED_KERNELS))
    for fn_name in untested:
        _invoke_and_compare(fn_name)
        TESTED_KERNELS.add(fn_name)

    assert exported_callables.issubset(TESTED_KERNELS), (
        f"Untested kernels found: {exported_callables - TESTED_KERNELS}"
    )
