# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from physical_engine.protos import sim_bridge_pb2 as physical__engine_dot_protos_dot_sim__bridge__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in physical_engine/protos/sim_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimBridgeStub:
    """SimBridge — gRPC co-simulation interface between the JaCaMo cognitive
    layer and the Python physical engine.

    Architecture:
    - AdvanceTime: Unary synchronization barrier with embedded state vector.
    - RunBatchTest: Station 5 polarization curve sweep via Newton-Raphson.
    - HealthCheck: JIT warmup status polling (500ms fixed interval).

    Reference: doc4 §2, doc6 §3.1

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdvanceTime = channel.unary_unary(
                '/factory.SimBridge/AdvanceTime',
                request_serializer=physical__engine_dot_protos_dot_sim__bridge__pb2.TimeStep.SerializeToString,
                response_deserializer=physical__engine_dot_protos_dot_sim__bridge__pb2.StepReady.FromString,
                _registered_method=True)
        self.RunBatchTest = channel.unary_unary(
                '/factory.SimBridge/RunBatchTest',
                request_serializer=physical__engine_dot_protos_dot_sim__bridge__pb2.BatchTestRequest.SerializeToString,
                response_deserializer=physical__engine_dot_protos_dot_sim__bridge__pb2.BatchTestResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/factory.SimBridge/HealthCheck',
                request_serializer=physical__engine_dot_protos_dot_sim__bridge__pb2.Empty.SerializeToString,
                response_deserializer=physical__engine_dot_protos_dot_sim__bridge__pb2.HealthStatus.FromString,
                _registered_method=True)


class SimBridgeServicer:
    """SimBridge — gRPC co-simulation interface between the JaCaMo cognitive
    layer and the Python physical engine.

    Architecture:
    - AdvanceTime: Unary synchronization barrier with embedded state vector.
    - RunBatchTest: Station 5 polarization curve sweep via Newton-Raphson.
    - HealthCheck: JIT warmup status polling (500ms fixed interval).

    Reference: doc4 §2, doc6 §3.1

    """

    def AdvanceTime(self, request, context):
        """Time Synchronization Barrier (Unary RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBatchTest(self, request, context):
        """Batch testing interface for polarization curve sweeping
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Warmup validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdvanceTime': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceTime,
                    request_deserializer=physical__engine_dot_protos_dot_sim__bridge__pb2.TimeStep.FromString,
                    response_serializer=physical__engine_dot_protos_dot_sim__bridge__pb2.StepReady.SerializeToString,
            ),
            'RunBatchTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBatchTest,
                    request_deserializer=physical__engine_dot_protos_dot_sim__bridge__pb2.BatchTestRequest.FromString,
                    response_serializer=physical__engine_dot_protos_dot_sim__bridge__pb2.BatchTestResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=physical__engine_dot_protos_dot_sim__bridge__pb2.Empty.FromString,
                    response_serializer=physical__engine_dot_protos_dot_sim__bridge__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'factory.SimBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('factory.SimBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimBridge:
    """SimBridge — gRPC co-simulation interface between the JaCaMo cognitive
    layer and the Python physical engine.

    Architecture:
    - AdvanceTime: Unary synchronization barrier with embedded state vector.
    - RunBatchTest: Station 5 polarization curve sweep via Newton-Raphson.
    - HealthCheck: JIT warmup status polling (500ms fixed interval).

    Reference: doc4 §2, doc6 §3.1

    """

    @staticmethod
    def AdvanceTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factory.SimBridge/AdvanceTime',
            physical__engine_dot_protos_dot_sim__bridge__pb2.TimeStep.SerializeToString,
            physical__engine_dot_protos_dot_sim__bridge__pb2.StepReady.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBatchTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factory.SimBridge/RunBatchTest',
            physical__engine_dot_protos_dot_sim__bridge__pb2.BatchTestRequest.SerializeToString,
            physical__engine_dot_protos_dot_sim__bridge__pb2.BatchTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/factory.SimBridge/HealthCheck',
            physical__engine_dot_protos_dot_sim__bridge__pb2.Empty.SerializeToString,
            physical__engine_dot_protos_dot_sim__bridge__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
