# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: physical_engine/protos/sim_bridge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'physical_engine/protos/sim_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'physical_engine/protos/sim_bridge.proto\x12\x07\x66\x61\x63tory\"B\n\x08TimeStep\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\x01\x12\n\n\x02\x64t\x18\x02 \x01(\x01\x12\x14\n\x0cschema_epoch\x18\x03 \x01(\x05\"K\n\tStepReady\x12\x13\n\x0btarget_time\x18\x01 \x01(\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x18\n\x0cstate_vector\x18\x03 \x03(\x01\x42\x02\x10\x01\"\xae\x01\n\x10\x42\x61tchTestRequest\x12\x10\n\x08stack_id\x18\x01 \x01(\t\x12\x11\n\tnum_cells\x18\x02 \x01(\x05\x12\x18\n\x10operating_temp_k\x18\x03 \x01(\x01\x12\x1d\n\x15inlet_pressure_h2_bar\x18\x04 \x01(\x01\x12\x1d\n\x15inlet_pressure_o2_bar\x18\x05 \x01(\x01\x12\x1d\n\x11\x63urrent_densities\x18\x06 \x03(\x01\x42\x02\x10\x01\"Y\n\x11\x42\x61tchTestResponse\x12\x0e\n\x06passed\x18\x01 \x01(\x08\x12\x1d\n\x11measured_voltages\x18\x02 \x03(\x01\x42\x02\x10\x01\x12\x15\n\rfailure_flags\x18\x03 \x01(\r\"\x07\n\x05\x45mpty\"\x1d\n\x0cHealthStatus\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\xbe\x01\n\tSimBridge\x12\x34\n\x0b\x41\x64vanceTime\x12\x11.factory.TimeStep\x1a\x12.factory.StepReady\x12\x45\n\x0cRunBatchTest\x12\x19.factory.BatchTestRequest\x1a\x1a.factory.BatchTestResponse\x12\x34\n\x0bHealthCheck\x12\x0e.factory.Empty\x1a\x15.factory.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'physical_engine.protos.sim_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEPREADY'].fields_by_name['state_vector']._loaded_options = None
  _globals['_STEPREADY'].fields_by_name['state_vector']._serialized_options = b'\020\001'
  _globals['_BATCHTESTREQUEST'].fields_by_name['current_densities']._loaded_options = None
  _globals['_BATCHTESTREQUEST'].fields_by_name['current_densities']._serialized_options = b'\020\001'
  _globals['_BATCHTESTRESPONSE'].fields_by_name['measured_voltages']._loaded_options = None
  _globals['_BATCHTESTRESPONSE'].fields_by_name['measured_voltages']._serialized_options = b'\020\001'
  _globals['_TIMESTEP']._serialized_start=52
  _globals['_TIMESTEP']._serialized_end=118
  _globals['_STEPREADY']._serialized_start=120
  _globals['_STEPREADY']._serialized_end=195
  _globals['_BATCHTESTREQUEST']._serialized_start=198
  _globals['_BATCHTESTREQUEST']._serialized_end=372
  _globals['_BATCHTESTRESPONSE']._serialized_start=374
  _globals['_BATCHTESTRESPONSE']._serialized_end=463
  _globals['_EMPTY']._serialized_start=465
  _globals['_EMPTY']._serialized_end=472
  _globals['_HEALTHSTATUS']._serialized_start=474
  _globals['_HEALTHSTATUS']._serialized_end=503
  _globals['_SIMBRIDGE']._serialized_start=506
  _globals['_SIMBRIDGE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
